name: cd

on:
  push:
    branches:
      - main

jobs:
  publish-to-maven-registry:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-west-3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to AWS CodeArtifact
        id: login-codeartifact
        run: |
          CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain ${{ secrets.CODEARTIFACT_DOMAIN }} --domain-owner ${{ secrets.CODEARTIFACT_DOMAIN_OWNER }} --query authorizationToken --output text)
          echo "CODEARTIFACT_AUTH_TOKEN=${CODEARTIFACT_AUTH_TOKEN}" >> $GITHUB_ENV

      - name: Setup Maven settings
        run: |
          mkdir -p ~/.m2
          echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd"><servers><server><id>codeartifact</id><username>aws</username><password>'${CODEARTIFACT_AUTH_TOKEN}'</password></server></servers></settings>' > ~/.m2/settings.xml  

      - name: Publish to CodeArtifact
        run: |
          mvn deploy -DaltDeploymentRepository=codeartifact::default::https://${{ secrets.CODEARTIFACT_DOMAIN }}-${{ secrets.CODEARTIFACT_DOMAIN_OWNER }}.d.codeartifact.${{ env.AWS_REGION }}.amazonaws.com/maven/${{ secrets.CODEARTIFACT_REPOSITORY }}/ \
          -Daws.codeartifact.token=${{ env.CODEARTIFACT_AUTH_TOKEN }} -DskipTests