name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.13.0
        with:
          java-version: '21'
          java-distribution: 'temurin'
          maven-version: '3.9.6'

      - name: Make format.sh executable
        run: chmod +x format.sh

      - name: Run format.sh
        run: ./format.sh

